## Introduction to Numpy

### Creating ndarray
An ndarray can be created from a list or tuple object

In [4]:
import numpy

In [5]:
import numpy as np

oneDim = np.array([1.0, 2, 3, 4, 5])
print(oneDim)
print("#Dimensions =", oneDim.ndim) # .ndim = number of dimention
print("Dimension =", oneDim.shape) # .shape = (행, 열)
print("Size =", oneDim.size) # .size = 원소 개수
print("Array type =", oneDim.dtype) # .dtype = data type(only one datatype)

[1. 2. 3. 4. 5.]
#Dimensions = 1
Dimension = (5,)
Size = 5
Array type = float64


numpy element has only one type like C array

In [3]:
twoDim = np.array([[1,2],[3,4],[5,6],[7,8]])
print(twoDim)
print("#Dimensions =", twoDim.ndim) # .ndim = number of dimention
print("Dimension =", twoDim.shape) # .shape = (행, 열)
print("Size =", twoDim.size) # .size = 원소 개수
print("Array type =", twoDim.dtype) # .dtype = data type(only one datatype)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
#Dimensions = 2
Dimension = (4, 2)
Size = 8
Array type = int32


In [4]:
arrFromTuple = np.array([(1, 'a', 3.0), (2, 'b', 3.5)])
print(arrFromTuple)
print("#Dimensions =", arrFromTuple.ndim) # .ndim = number of dimention
print("Dimension =", arrFromTuple.shape) # .shape = (행, 열)
print("Size =", arrFromTuple.size) # .size = 원소 개수
print("Array type =", arrFromTuple.dtype) # .dtype = data type(only one datatype)

[['1' 'a' '3.0']
 ['2' 'b' '3.5']]
#Dimensions = 2
Dimension = (2, 3)
Size = 6
Array type = <U11


In [5]:
print(np.array([1]).shape)
print(np.array([1,2]).shape)
print(np.array([[1], [2]]).shape)

print(np.array([[[1,2,3],[1,2,3]]]).shape)
print(np.array([[[1,2,3],[1,2,3]], [[4,5,6],[4,5,6]]]).shape)
print(np.array([[[1,2,3],[1,2,3],[1,2,3]]]).shape)
print(np.array([[[1,2],[1,2]]]).shape)

print(np.array([[[[]]]]).shape)
print(np.array([[[[0]]]]).shape)
print(np.array([[[[0,2]]]]).shape)

(1,)
(2,)
(2, 1)
(1, 2, 3)
(2, 2, 3)
(1, 3, 3)
(1, 2, 2)
(1, 1, 1, 0)
(1, 1, 1, 1)
(1, 1, 1, 2)


In [6]:
(1,2) == (1,2,)

True

In [7]:
print(np.random.rand(5)) # [0,1] 사이의 랜덤
print(np.random.randn(5)) # 정규분포...
print(np.arange(-10,10,2)) # -10~9 중에서 2씩 뛰어서
print(np.arange(12).reshape(3,4)) # 0~11 을 (3,4) 배열로
print(np.linspace(0,1,10)) # [0,1] 10등분
print(np.linspace(0,1,5))

print(np.logspace(-3,3,7)) # 지수함수의 지수가 [-3,3]의 7등분(아마 7등분...)
print(np.logspace(-3,3,9))

[0.31743443 0.87582362 0.61500291 0.3343099  0.01703746]
[ 0.05761502  0.12895835  1.21809354  0.31663865 -0.40379189]
[-10  -8  -6  -4  -2   0   2   4   6   8]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.   0.25 0.5  0.75 1.  ]
[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]
[1.00000000e-03 5.62341325e-03 3.16227766e-02 1.77827941e-01
 1.00000000e+00 5.62341325e+00 3.16227766e+01 1.77827941e+02
 1.00000000e+03]


In [8]:
print(np.zeros((2,3))) # .zeros(row, column) = zeros matrix (row, column)
print(np.ones((3,2))) # .ones(row,column) = ones matrix (row, column)
print(np.eye(3)) # n x n의 단위행렬

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Element-wise Operations
You can apply standard operators such as addition and multiplication on each elemnet of the ndarray.

In [9]:
x = np.array([1,2,3,4,5])
# 연산들은 모든 원소들에 적용된다. # 행렬 간격 일정함. 그래서 긴 숫자 나오면 그거에 맞춤
print(x + 1)
print(x - 1)
print(x * 2)
print(x / 2) # 나눗셈 (실수 반환인듯)
print(x // 2) # 몫 나눗셈 (정수 반환인듯)
print(x ** 2) # 제곱
print(x % 2) # 나머지 나눗셈
print(1 / x)

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]
[ 1  4  9 16 25]
[1 0 1 0 1]
[1.         0.5        0.33333333 0.25       0.2       ]


In [10]:
x = np.array([2,4,6,8,10])
y = np.array([1,2,3,4,5])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x // y)
print(x % y)
#print(x & y)
print(x ** y)

[ 3  6  9 12 15]
[1 2 3 4 5]
[ 2  8 18 32 50]
[2. 2. 2. 2. 2.]
[2 2 2 2 2]
[0 0 0 0 0]
[     2     16    216   4096 100000]


## Indexing and Slicing
There are various ways to select certain elements with an ndarray.

In [11]:
x = np.arange(-5, 5) # -5~4  # (1,)
print(x)

y = x[3:5] # [3], [4]
print(y)
y[:] = 1000 # 1000 1000  # [3] -> 1000, [4] -> 1000
print(y)
print(x)

z = x[3:5].copy() # 이건 copy
print(z) # 1000 1000
z[:] = 500 # 500 500  # 하지만 원본은 변하지 않지
print(z)
print(x)

[-5 -4 -3 -2 -1  0  1  2  3  4]
[-2 -1]
[1000 1000]
[  -5   -4   -3 1000 1000    0    1    2    3    4]
[1000 1000]
[500 500]
[  -5   -4   -3 1000 1000    0    1    2    3    4]



#### Remark: slicing a list makes a copy of the sublist, but slicing numpy array does not.

In [12]:
#Remark slicing a list makes a copy of the sublist
x = list(range(-5, 5)) # -5 ~ 4 리스트
print(x)

y = x[3:5] # [3] [4] 리스트
print(y)
y[1] = 1000 # [3] 1000 # copy본이라서 원본은 안 바뀜
print(y)
print(x)

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]
[-2, -1]
[-2, 1000]
[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]


In [13]:
my2dlist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] # list
print(my2dlist)
print(my2dlist[2])
print(my2dlist[:][2])
# print(my2dlist[1:2][2]) # syntax error
# print(my2dlist[:,2])  # syntax error
print(my2dlist[2][1])

print()

my2darr = np.array(my2dlist)  # numpy
print(my2darr)
print()
print(my2darr[2][:])
print(my2darr[2,:])
print()
print(my2darr[:][2])
print(my2darr[:][:][2])
print(my2darr[:][2][:])
print()
print(my2darr[:][:][2,3])
print()
print(my2darr[:,2])
print(my2darr[:2,2:])
print(my2darr[:1,2:])
print(my2darr[::2,2:])
print(my2darr[::2,::3])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]
[9, 10, 11, 12]
10

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 9 10 11 12]
[ 9 10 11 12]

[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]

12

[ 3  7 11]
[[3 4]
 [7 8]]
[[3 4]]
[[ 3  4]
 [11 12]]
[[ 1  4]
 [ 9 12]]



### Remark again: It's indexing, not copying

In [14]:
my2darr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #(3,4)
print(my2darr)

print()
sliced = my2darr[::2,2:] # row 0,2 column 2,3 # indexing
print(sliced)
print(type(sliced))

print()
sliced[:,:] = 1000 # [[1000 1000] [1000 1000]] # 원본도 변화됨
print(my2darr)

print()
sliced[0,0] = 2000 # [[2000 1000] [1000 1000]] # 원본도 변화됨
print(my2darr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 3  4]
 [11 12]]
<class 'numpy.ndarray'>

[[   1    2 1000 1000]
 [   5    6    7    8]
 [   9   10 1000 1000]]

[[   1    2 2000 1000]
 [   5    6    7    8]
 [   9   10 1000 1000]]



### ndarray also supports boolean indexing (also called masking).

In [15]:
# slicing vs masking vs integer array indexing
x =  np.array([1,2,3])
print(x[1:])
print(x[1:][0])
print(x)
print(x.shape)

print()
print(x[[True, False, True]]) # boolean masking # True인 값만 지칭하겠다.

print()
print(x[[2,1]]) # integer array indexing # [2] [1] = 3 2
# (2,1)이 출력하고 싶다면 x[2,1] # 물론 여기서는 불가능
print(x[[2,1,1,1,0]]) # [2] [1] [1] [1] [0] = 3 2 2 2 1

print()
x[[2,1,1,1]] = 0 # 지정한 index의 원소 값 바꿔버림
print(x)
x[[1,0,0]] = 7
print(x)

[2 3]
2
[1 2 3]
(3,)

[1 3]

[3 2]
[3 2 2 2 1]

[1 0 0]
[7 7 0]


In [16]:
y = np.arange(35).reshape(5,7)  # 0~34
print(y)
print()
b = y > 20 # 이 순간 True와 False로 나뉘게 된다!
print(b)
#b = y <= 20
#print()
#print(b)

print()
t = y[b]  # b조건을 만족하는 원소들의 배열같다.... # 이건 copy다. indexing 아님
# Filtering result is always ond-dimensional
print(t)

print()
t[:3] = 1000 # copy본이라서 원본 안 바뀌고 자신만 바뀜
print(t)
print(y)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]

[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]

[21 22 23 24 25 26 27 28 29 30 31 32 33 34]

[1000 1000 1000   24   25   26   27   28   29   30   31   32   33   34]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [17]:
M = np.arange(35).reshape(5,7)
M

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [18]:
M[M % 2 == 0] = 0 # index말고 "자료"가 짝수면 0으로 만들어버리기
M

array([[ 0,  1,  0,  3,  0,  5,  0],
       [ 7,  0,  9,  0, 11,  0, 13],
       [ 0, 15,  0, 17,  0, 19,  0],
       [21,  0, 23,  0, 25,  0, 27],
       [ 0, 29,  0, 31,  0, 33,  0]])

In [19]:
M[M % 2 == 0] = -M[M % 2 == 0] # 뭔가...극적인걸 기대했겠지만! 이건 짝수가 다 0
M

array([[ 0,  1,  0,  3,  0,  5,  0],
       [ 7,  0,  9,  0, 11,  0, 13],
       [ 0, 15,  0, 17,  0, 19,  0],
       [21,  0, 23,  0, 25,  0, 27],
       [ 0, 29,  0, 31,  0, 33,  0]])

In [20]:
M[M % 2 != 0] = -M[M % 2 != 0]
M

array([[  0,  -1,   0,  -3,   0,  -5,   0],
       [ -7,   0,  -9,   0, -11,   0, -13],
       [  0, -15,   0, -17,   0, -19,   0],
       [-21,   0, -23,   0, -25,   0, -27],
       [  0, -29,   0, -31,   0, -33,   0]])

In [21]:
N = np.array([[1, 1, 4, 5],[2,1,1,5]])
N[N % 2 == 0] = -N[N % 2 == 0] # 값이 짝수인 원소만 부호바꿔줌
N

array([[ 1,  1, -4,  5],
       [-2,  1,  1,  5]])

In [22]:
# First Boolean masking

np.where(M % 2 == 0, M, -M) # (조건, 조건 만족하면 분리할 것, 가하는 타겟? 효과)

array([[ 0,  1,  0,  3,  0,  5,  0],
       [ 7,  0,  9,  0, 11,  0, 13],
       [ 0, 15,  0, 17,  0, 19,  0],
       [21,  0, 23,  0, 25,  0, 27],
       [ 0, 29,  0, 31,  0, 33,  0]])

In [23]:
my2darr = np.arange(1,13,1).reshape(4,3) # 1~12
print(my2darr)
print()
indices = [2,1,0,3]  # row 원하는 순서
print(my2darr[indices,:]) # integer array indexing 놀이 그거랑 비슷한거 같다.
print()
rowIndex = [0,0,1,2,3] # row 원하는 순서
columnIndex = [0,2,0,1,2] # column 원하는 순서
print(my2darr[rowIndex,columnIndex]) # 원하는 순서에 해당하는 애들 출력

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]

[ 1  3  4  8 12]


## Numpy Arithmeic and Statistical Functions
There are many built-in mathematical functions available for manipulating elements of nd-array.

In [24]:
y = np.array([-1.4, 0.4, -3.2, 2.5, 3.4])
print(y)
print()

print(np.abs(y))  # .abs = absolute. 절대값으로 바꿈
print(np.sqrt(np.abs(y))) # .sqrt(.abs()) = 절대값으로 바꾼거의 제곱근 값
print(np.sign(y)) # .sign = 음수인지(-1.) 0인지(0.) 양수인지(1.)
print(np.exp(y)) # .exp =  e^y
print(np.sort(y)) # .sort() = return sorted copy

print(y)  # y는 변하지 않아

[-1.4  0.4 -3.2  2.5  3.4]

[1.4 0.4 3.2 2.5 3.4]
[1.18321596 0.63245553 1.78885438 1.58113883 1.84390889]
[-1.  1. -1.  1.  1.]
[ 0.24659696  1.4918247   0.0407622  12.18249396 29.96410005]
[-3.2 -1.4  0.4  2.5  3.4]
[-1.4  0.4 -3.2  2.5  3.4]


In [25]:
x = np.arange(-2,3)
y = np.random.randn(5)
print(x)
print(y)

print(np.add(x,y))  # x+y
print(np.subtract(x,y)) # x-y
print(np.multiply(x,y)) # x*y
print(np.divide(x,y)) # x/y
print(np.maximum(x,y)) # max(x,y)

[-2 -1  0  1  2]
[ 0.90445317 -0.02913316  0.75598608  2.00784477 -0.82303122]
[-1.09554683 -1.02913316  0.75598608  3.00784477  1.17696878]
[-2.90445317 -0.97086684 -0.75598608 -1.00784477  2.82303122]
[-1.80890635  0.02913316  0.          2.00784477 -1.64606245]
[-2.21128087 34.32514725  0.          0.49804647 -2.43004146]
[ 0.90445317 -0.02913316  0.75598608  2.00784477  2.        ]


In [26]:
y = np.array([-3.2, -1.4, 0.4, 2.5, 3.4])
print(y)

print("Min =", np.min(y)) # min
print("Max =", np.max(y)) # max
print("Average =", np.mean(y)) # maen(average)
print("Std deviation =", np.std(y)) # standard deviation 표준편차
print("Sum =", np.sum(y)) # sum

[-3.2 -1.4  0.4  2.5  3.4]
Min = -3.2
Max = 3.4
Average = 0.34000000000000014
Std deviation = 2.432776191925595
Sum = 1.7000000000000006



### More on filtering

In [27]:
M = np.arange(25).reshape(5,5)
print(M)
print(M[M % 2 == 1])
print(np.argwhere(M >= 20)) # 조건을 만족시키는 인덱스를 반환
print(np.where(M % 2 == 1, M, 0)) # 조건을 만족시키는 거 제외하고 다 0으로 바꿔버림

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 1  3  5  7  9 11 13 15 17 19 21 23]
[[4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]]
[[ 0  1  0  3  0]
 [ 5  0  7  0  9]
 [ 0 11  0 13  0]
 [15  0 17  0 19]
 [ 0 21  0 23  0]]


### New axis
- Used to increase the dimension of the existing array by one more dimension
- shape change, for example: n x (newaxis) x m => n x 1 x m

In [6]:
t = np.array([1,2,3])
print(t.shape)
x = t[:, np.newaxis]
print(x.shape)
y = t[np.newaxis, :]
print(y.shape)
z = x[:, np.newaxis]
print(z.shape)
w = y[np.newaxis, :]
print(w.shape)

(3,)
(3, 1)
(1, 3)
(3, 1, 1)
(1, 1, 3)


In [7]:
print(t)
print(x)
print(y)
print(z)
print(w)
print(y[:, np.newaxis])

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]]
[[[1]]

 [[2]]

 [[3]]]
[[[1 2 3]]]
[[[1 2 3]]]


In [8]:
t = np.array([1, 2, 3])
print(t[np.newaxis, :, np.newaxis])

[[[1]
  [2]
  [3]]]


In [34]:
x + y # 결과에 콤마가 있다. 리스트의 계산을 한 것처럼 되었다.

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [36]:
t = np.array([[1,2,3],[4,5,6]])
print(t.shape) # (2,3)
print()
print(t[:, :, np.newaxis].shape) # (2,3,1)
print(t[:, :, np.newaxis])  # 원본이 변형되지는 않는 것 같다.
print()

print(t[np.newaxis, :, :].shape) #(1, 2, 3)
print(t[np.newaxis, :, :])

print()
print(t[:, np.newaxis, :])

(2, 3)

(2, 3, 1)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]

(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]

[[[1 2 3]]

 [[4 5 6]]]


### n-d array axis view

# 1D array   2D array   3D array

## Broadcasting
Broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is“broadcast” across the larger array so that they have compatible shapes.

Examples:
   
    A      (2d array): 5 x 4
    B      (1d array):     1
    Result (2d array): 5 x 4

    A      (2d array): 5 x 4
    B      (1d array):     4
    Result (2d array): 5 x 4
    
    A      (3d array): 15 x 3 x 5
    B      (3d array): 15 x 1 x 5
    Result (3d array): 15 x 3 x 5
    
    A      (3d array): 15 x 3 x 5
    B      (2d array):      3 x 5
    Result (3d array): 15 x 3 x 5
    
    A      (3d array): 15 x 3 x 5
    B      (2d array):      3 x 1
    Result (3d array): 15 x 3 x 5

In [37]:
np.array([[1,2],[3,4]]) + np.array([[10]]) # (2, 2) + (1, 1)

array([[11, 12],
       [13, 14]])

In [39]:
np.array([[1,2],[3,4]]) + np.array([[10,100]]) # (2, 2) + (1, 2)

array([[ 11, 102],
       [ 13, 104]])

In [40]:
np.array([[1,2],[3,4]]) + np.array([[10],[100]]) # (2, 2) + (2, 1)

array([[ 11,  12],
       [103, 104]])

In [41]:
A = np.array([[1,2]])
B = np.array([[10],[100]])
print(A.shape, B.shape)
C = A + B
C

(1, 2) (2, 1)


array([[ 11,  12],
       [101, 102]])

In [43]:
X = np.array([[1]]*3) + np.array([[0]*10]) # (3, 1) + (1, 10)
# 바깥쪽에 곱할 수록...작은 축이랄까
# broadcasting을 통해서 행렬의 자료양?길이?를  필요한만큼 늘릴 수 있을 것 같다.
X

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [44]:
a = np.array([[1],[2],[3]]) # (3, 1)
b = a.T # 전치행렬 (a, b) -> (b, a) # [i, j] -> [j, i]
a + b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

### Meshgrid
Make D x N mesh grid for vectorized evaluations

In [46]:
v = np.array([10,20,30]) # N # (, 3)
w = np.array([5,6]) # D # (, 2)
X, Y = np.meshgrid(v, w) # (가로, 세로)의 직사각형 격자랄까. 아마 배열.
Z, W = np.meshgrid(w, v)
print(X + Y)
print(Z + W)

[[15 25 35]
 [16 26 36]]
[[15 16]
 [25 26]
 [35 36]]


### Axis ordering
   - By definition, the axis number of the dimension is the index of that dimension within the array's shape. It is also the position used to access that dimension during indexing.

   - For example, if a 2D array a has shape (5,6), then you can access a[0,0] up to a[4,5]. Axis 0 is thus the first dimension (the "rows"), and axis 1 is the second dimension (the "columns"). In higher dimensions, where "row" and "column" stop really making sense, try to think of the axes in terms of the shapes and indices involved.

   - If you do np.sum(axis=n), for example, then dimension n is collapsed and deleted, with each value in the new matrix equal to the sum of the corresponding collapsed values. For example, if b has shape (5,6,7,8), and you do c = b.sum(axis=2), then axis 2 (dimension with size 7) is collapsed, and the result has shape (5,6,8). Furthermore, c[x,y,z] is equal to the sum of all elements b[x,y,:,z].


In [47]:
X = np.array([[0,0,0],[1,1,1]])
X.shape # (2,3) (axis0, axis1)

(2, 3)

In [48]:
X.sum(axis=0) # axis0 방향으로 sum # [1,1,1]
# shape도 바뀌고 더이상 행렬이 아닌듯. 값의 배열

array([1, 1, 1])

In [49]:
X.sum(axis=1) # axis1 방향으로 sum # [0, 3]

array([0, 3])

In [50]:
X = np.array(range(1,24+1)).reshape(2,3,4) # (1~24) (2, 3, 4)
"""
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]
  
 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
"""
X

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [51]:
X.shape

(2, 3, 4)

In [52]:
X.sum(axis=0) # 3 x 4 배열

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [53]:
X.sum(axis=1) # 2 x 4

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [55]:
X.sum(axis=2) # 2 x 3

array([[10, 26, 42],
       [58, 74, 90]])

In [56]:
X.sum(axis=(1,2)) # 2

array([ 78, 222])

In [57]:
X.sum(axis=(0,1,2)) # sum ALL

300

In [58]:
X = np.array([0,0,0])
Y = np.array([1,1,1])

np.sqrt(np.sum((X - Y)**2)) # 3차원 공간 두 점 사이의 거리

1.7320508075688772

In [61]:
import numpy as np
X = np.array(np.arange(2*3, 0, -1).reshape(2,3)) # 6,5,4,3,2,1 # (2,3)
print(X)
print()
print("axis=0\n", np.sort(X, axis=0))
print()
print("axis=1\n", np.sort(X, axis=1))
print()
print("default is -1\n", np.sort(X)) # -1번째 축은 마지막 축을 의미
print()
print("axis=0,1\n", np.sort(np.sort(X, axis=0), axis=1))
# 전체 sort # axis=(0,1)같은 표현은 여기서는 안되는 것 같다.
print()
print("axis=None\n", np.sort(X, axis=None)) # 축이 없는 상황처럼?? sort?

[[6 5 4]
 [3 2 1]]

axis=0
 [[3 2 1]
 [6 5 4]]

axis=1
 [[4 5 6]
 [1 2 3]]

default is -1
 [[4 5 6]
 [1 2 3]]

axis=0,1
 [[1 2 3]
 [4 5 6]]

axis=None
 [1 2 3 4 5 6]


#### sort vs argsort vs partition vs argpartition
   - argmin, argmax, ...

In [9]:
X = np.array([4,10,1,20,45,100,2,1])
print('X =\n', X)
print('sorted =\n', np.sort(X))
print('argsorted =\n', np.argsort(X)) # sort됐을때의 index랄까

# partition : 순서가 상관이 없음. 대소관계. (unstable? 할수도....)
# k번째보다 작은것 / k번째 / k번째와 같거나 k번째보다 큰것
# k번째가 index인가 진짜 순서인가 => 진짜 순서다! // ?? 아닐 수도
# 정확한 동작 순서는 아직 잘 모름.
print('partitioned first 3 =\n', np.partition(X, 3))
print('argpartitioned first 3 =\n', np.argpartition(X, 3)) # index
print(X[3])
print(np.partition(X,3)[3])
print()
print(X[4])
print(np.partition(X,4))
print(np.partition(X,4)[4])
print()
print(np.partition(X,5))
print(np.partition(X,5)[5])
print()
print(np.partition(X,6))
print(np.partition(X,6)[6])
print()
print()
print(np.partition(X,0))
print(np.partition(X,0)[0])
print()
print(np.partition(X,1))
print(np.partition(X,1)[1])
print()
print(np.partition(X,2))
print(np.partition(X,2)[2])
print()
print(np.partition(X,3))
print(np.partition(X,3)[3])
print()

print('partitioned last 3=\n', np.partition(X, -3))
print('argpartitioned last 3=\n', np.argpartition(X, -3))

X =
 [  4  10   1  20  45 100   2   1]
sorted =
 [  1   1   2   4  10  20  45 100]
argsorted =
 [2 7 6 0 1 3 4 5]
partitioned first 3 =
 [  2   1   1   4  45 100  10  20]
argpartitioned first 3 =
 [6 7 2 0 4 5 1 3]
20
4

45
[  2   1   1   4  10  20  45 100]
10

[  2   1   1   4  10  20  45 100]
20

[  2   1   1   4  10  20  45 100]
45


[  1  10   4  20  45 100   2   1]
1

[  1   1   4  20  45 100   2  10]
1

[  1   1   2  20  45 100   4  10]
2

[  2   1   1   4  45 100  10  20]
4

partitioned last 3=
 [  2   1   1   4  10  20  45 100]
argpartitioned last 3=
 [6 7 2 0 1 3 4 5]


In [66]:
# numpy에서 원하는 (행/열)순서로 배열 뽑기
# 표현이 좀 특이함
T = np.array([[2.2],[-1,10],[0,1]]) # (3,2)
I = np.argsort(np.sum(T, axis=1))  # 왜 오류나지
# array([4, 9, 1])인데, 이걸로 numpy화
# [4 9 1]을 sort했을 때의 index numpy가 I = [2 0 1]

T[I,:]
# I의 원소 넘버 순서?대로 T의 행(row)을 나열?한달까. ':'이라서 열(column)은 그대로

AxisError: axis 1 is out of bounds for array of dimension 1

### Vectorized function

- similar to map function

In [3]:
u = np.array([100, 2, 3, 4])
v = np.array([1, 2, 3, 4])
w = np.array([4,3,2,1])
np.vectorize(max)(u, v, w) # 100, 1, 4 중 max # 2, 2, 3 중 max #.... #....그래서 4개

array([100,   3,   3,   4])

In [4]:
dist = np.vectorize(lambda x, y: np.sqrt(x**2 + y**2))
dist(v, w)

array([4.12310563, 3.60555128, 3.60555128, 4.12310563])

### Numpy Linear algebra
Numpy provides many functions to support linear algebra operations.

In [5]:
X = np.random.randn(2,3)
print(X)
print(X.T)
print()
y = np.random.randn(3)
print(y) # 이거 dimention = 1이라서  y*y하면 걍 스칼라 값 나옴. 내적.
print()
print(X.dot(y)) # dot product (내적) # X * y # 교수님은 이 표현이 더 좋다고 하심.
print()
print(np.dot(X,y)) # 이렇게도 표현가능
print()
print(X.dot(X.T)) # X * X^T
print()
print(X.T.dot(X)) # X^T * X

[[ 0.3202549   0.91373282 -1.80760306]
 [ 0.96395464  0.48605335 -1.01538412]]
[[ 0.3202549   0.96395464]
 [ 0.91373282  0.48605335]
 [-1.80760306 -1.01538412]]

[-0.14069893 -1.31817131  0.00904682]

[-1.26586898 -0.78551497]

[-1.26586898 -0.78551497]

[[4.20489968 2.58824552]
 [2.58824552 2.1964613 ]]

[[ 1.03177175  0.76116079 -1.55767797]
 [ 0.76116079  1.07115552 -2.14519709]
 [-1.55767797 -2.14519709  4.29843371]]


In [6]:
X = np.random.randn(5,3)
print(X)

C = X.T.dot(X)

invC = np.linalg.inv(C) # inverse # 역행렬
print(invC)
detC = np.linalg.det(C) # determinant # 행렬식 구하는거
print(detC)
S, U = np.linalg.eig(C) # eigenvector # 고유벡터 # 1st,2nd = eigenvalue,eigenvector
print(S)
print(U)

[[-0.62052898 -1.20518248 -1.13066841]
 [-1.02462283 -0.21994259  0.38561205]
 [-0.72242454 -0.44047425  0.65140395]
 [ 0.45428264  1.76028533 -0.82650193]
 [-0.23350046 -0.10169276 -1.02217782]]
[[ 0.78066515 -0.34133586  0.03128907]
 [-0.34133586  0.35899415  0.00741548]
 [ 0.03128907  0.00741548  0.28275328]]
21.859650535677456
[1.02896867 6.07483368 3.4970889 ]
[[-0.87329428  0.48362066  0.05889113]
 [ 0.48597546  0.85618328  0.17543673]
 [-0.03442323 -0.18182754  0.98272773]]


### The Frobenius norm

In [ ]:
X = np.array([1,2])
print(np.linalg.norm(X))
print(np.linalg.norm(X, ord=1))
print(np.linalg.norm(X, ord=np.inf))
print(np.linalg.norm(X, ord=-np.inf))

In [ ]:
import math
x = np.array([1,0])
y = np.array([0,1])
print("cosine =", x.dot(y) / (math.sqrt((x.dot(x))) * math.sqrt((y.dot(y)))))
print("cosine =", x.dot(y) / (np.linalg.norm(x) * np.linalg.norm(y)))

### Lab: distance matrix

In case of 1-d points

In [ ]:
pts = np.array([1.,2,3,4,5])
u = pts[:, np.newaxis]
v = pts.T[np.newaxis, :]
np.abs(u - v)

In case of n-d points

In [ ]:
pts = np.array([[1.0], [1,1], [0,1]])
print(pts.shape)
u = pts[:, :, np.newaxis]
v = pts.T[np.newaxis, :, :]

In [ ]:
print(v.shape)
print(u.shape)

In [ ]:
np.sqrt(np.sum((u - v)**2, axis=1))

In [ ]:
np.linalg.norm(u - v, axis=1)

- In your real application, use sklearn.metrics.pairwise to compute pairwise distances

In [ ]:
from sklearn.metrics.pairwise import euclidean_distances, manhattan_distances, cosin_similarity

print(euclidean_distances(pts))
print(manhattan_distances(pts))
print(cosine_similarity(pts))

- If you define your own distance

In [ ]:
from sklearn.metrics.pairwise import pairwise_distances

inf_dist = lambda x, y : np.max(np.abs(x - y))
print(pairwise_distances(pts, metric=inf_dist))